wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723554517
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      3:
      - 7
      - 23
      - 66
      4: 3.9.19
      5: 0.17.5
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: img_samples._type
      5: 1
      6:
      - 1
    - 1: img_samples.sha256
      5: 1
      6:
      - 1
    - 1: img_samples.size
      5: 1
      6:
      - 1
    - 1: img_samples.artifact_path
      5: 1
      6:
      - 1
    - 1: img_samples._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: img_samples.path
      5: 1
      6:
      - 1
    - 1: img_samples.ncols
      5: 1
      6:
      - 1
    - 1: img_samples.nrows
      5: 1
      6:
      - 1
